[package]
name = "swc_plugins_shared"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
convert_case = { workspace = true }
hex = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
sha-1 = { workspace = true }
sugar_path = { workspace = true }
swc_core = { workspace = true, features = ["ecma_ast", "ecma_utils", "swc_atoms"] }
