[package]
name = "swc_plugin_compat"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
convert_case = "0.6.0"
once_cell = "1.20.2"
regex = "1.11.1"
rustc-hash = "2.1.1"
serde = "1.0.216"
serde_json = "1.0.134"
swc_core = { version = "16.5.0", features = ["base", "ecma_plugin_transform", "ecma_visit", "ecma_utils", "ecma_quote", "ecma_parser"] }
ts-rs = "10.1.0"

# .cargo/config.toml defines few alias to build plugin.
# cargo build-wasi generates wasm-wasi32 binary
# cargo build-wasm32 generates wasm32-unknown-unknown binary.
