[package]
name = "swc_plugin_react_lynx"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
convert_case = "0.6.0"
hex = "0.4.3"
indexmap = "2.7.0"
once_cell = "1.20.2"
regex = "1.11.1"
rustc-hash = "2.1.1"
serde = "1.0.216"
serde_json = { version = "1.0.134", features = ["preserve_order"] }
sha-1 = "0.10"
swc_core = { version = "16.5.0", features = ["base", "ecma_codegen", "ecma_parser", "ecma_minifier", "ecma_transforms_typescript", "ecma_utils", "ecma_quote", "ecma_transforms_react", "ecma_transforms_optimization", "css_parser", "css_ast", "css_visit", "css_codegen", "__visit", "__testing_transform", "ecma_plugin_transform"] }
ts-rs = "10.1.0"
version-compare = "0.2.0"
