[net]
git-fetch-with-cli = true

# These command aliases are not final, may change
[alias]
# Alias to build actual plugin binary for the specified target.
build-wasm32 = "build --target wasm32-unknown-unknown"
build-wasi = "build --target wasm32-wasi"
