[package]
name = "swc_plugin_compat"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
convert_case = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
swc_core = { workspace = true, features = ["ecma_parser", "ecma_utils", "ecma_quote", "ecma_visit", "testing_transform"] }
swc_plugins_shared = { path = "../swc_plugins_shared" }
