[package]
name = "swc_plugin_dynamic_import"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
swc_core = { workspace = true, features = ["ecma_parser", "ecma_utils", "ecma_visit", "testing_transform"] }
swc_plugins_shared = { path = "../swc_plugins_shared" }
