[package]
name = "swc_plugin_list"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
swc_core = { workspace = true, features = ["ecma_parser", "ecma_utils", "ecma_quote", "ecma_visit", "testing_transform"] }
swc_plugin_snapshot = { path = "../swc_plugin_snapshot" }
swc_plugins_shared = { path = "../swc_plugins_shared" }
