name: Rust

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

# Set minimum permissions to prevent unnecessary access
permissions: {}

env:
  CI: 1
  TURBO_TELEMETRY_DISABLED: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test (${{ matrix.runs-on.name }})
    runs-on: ${{ matrix.runs-on.label }}
    strategy:
      matrix:
        runs-on:
          - label: lynx-ubuntu-24.04-xlarge
            name: Ubuntu
          # - label: lynx-windows-2022-large-verify
          #   name: Windows
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: ./.github/actions/rustup
        with:
          key: test
          save-if: ${{ github.ref_name == 'main' }}
      - name: Install llvm-cov and nextest
        uses: taiki-e/install-action@71b48393496777ee11188c07a34d48b048a985cd # v2
        with:
          tool: cargo-llvm-cov,cargo-nextest
      - name: Test
        env:
          CARGO_LLVM_COV_FLAGS_NO_RUNNER: --no-sparse
        run: |
          cargo llvm-cov nextest --all-features --profile ci --config-file .cargo/nextest.toml --lcov --output-path lcov.info  --release
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/test-report.junit.xml

  rustfmt:
    runs-on: lynx-ubuntu-24.04-medium
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1
        with:
          components: rustfmt
          cache: false
      - name: Format
        run: cargo fmt --check

  clippy:
    runs-on: lynx-ubuntu-24.04-medium
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1
        with:
          components: clippy
          cache: false
      - name: Clippy
        run: cargo clippy --tests --all-features -- -D warnings
